# Generated by Django 2.0.1 on 2018-03-19 03:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=10000)),
                ('first_name', models.TextField(max_length=100, null=True)),
                ('last_name', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.TextField(default='New Card', max_length=200)),
                ('text', models.TextField(default='Default text.', max_length=1000)),
                ('address_line_1', models.TextField(max_length=1000, null=True)),
                ('address_line_2', models.TextField(max_length=1000, null=True)),
                ('city', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New wallet', max_length=100)),
                ('card', models.ManyToManyField(to='cards.UserCard')),
            ],
        ),
        migrations.CreateModel(
            name='WatermarkUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.WatermarkUser'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.WatermarkUser'),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.UserCard'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cards.WatermarkUser'),
        ),
    ]
