# Generated by Django 2.0.1 on 2018-02-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_usercard_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='text',
            field=models.TextField(default='Default text.', max_length=1000),
        ),
    ]
