# Generated by Django 2.0.1 on 2018-02-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_usercard_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='card',
        ),
        migrations.AddField(
            model_name='wallet',
            name='card',
            field=models.ManyToManyField(to='cards.UserCard'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cards.WatermarkUser'),
        ),
    ]
