# Generated by Django 2.0.1 on 2018-03-05 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cards.UserCard'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
