# Generated by Django 2.0.1 on 2018-03-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20180305_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='address_line_1',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usercard',
            name='address_line_2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usercard',
            name='city',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usercard',
            name='name',
            field=models.TextField(default='New Card', max_length=200),
        ),
    ]
